name: Publish VS Code Extension

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4

    - name: Install dependencies
      run: npm install

    - name: Build the extension
      run: npm run build

    - name: Install vsce
      run: npm install -g vsce

    - name: Package the extension
      run: npm run pack

    - name: Publish to Visual Studio Code Marketplace
      run: vsce publish ./fantasies-npm-analysis.vsix
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}