name: Publish VS Code Extension

on:
  push:
    tags:
        - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4

    - name: Install dependencies
      run: npm install

    - name: Build the extension
      run: npm run build

    - name: Get tag version
      id: get_tag
      run: echo "TAG=${GITHUB_REF##*/}" | sed 's/^v//' >> $GITHUB_ENV

    - name: Package the extension
      run: npm run pack

    - name: Install vsce
      run: npm install -g vsce

    - name: Publish to Visual Studio Code Marketplace
      run: vsce  publish  ./fantasies-npm-analysis-${{ env.TAG }}.vsix
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}